[0.000000] (-) TimerEvent: {}
[0.000255] (-) JobUnselected: {'identifier': 'cartographer'}
[0.000452] (-) JobUnselected: {'identifier': 'cartographer_ros'}
[0.000476] (-) JobUnselected: {'identifier': 'cartographer_ros_msgs'}
[0.000494] (-) JobUnselected: {'identifier': 'cartographer_rviz'}
[0.000512] (-) JobUnselected: {'identifier': 'lidar_imu_correction'}
[0.000529] (-) JobUnselected: {'identifier': 'mpu6050_py'}
[0.000546] (-) JobUnselected: {'identifier': 'mpu6050driver'}
[0.000562] (-) JobUnselected: {'identifier': 'pointcloud_to_laserscan'}
[0.000578] (-) JobUnselected: {'identifier': 'slam_toolbox'}
[0.000594] (-) JobUnselected: {'identifier': 'sllidar_ros2'}
[0.000614] (scan_to_pointcloud) JobQueued: {'identifier': 'scan_to_pointcloud', 'dependencies': OrderedDict()}
[0.000893] (scan_to_pointcloud) JobStarted: {'identifier': 'scan_to_pointcloud'}
[0.099685] (-) TimerEvent: {}
[0.200038] (-) TimerEvent: {}
[0.300323] (-) TimerEvent: {}
[0.400781] (-) TimerEvent: {}
[0.501539] (-) TimerEvent: {}
[0.602000] (-) TimerEvent: {}
[0.630079] (scan_to_pointcloud) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 75, in execute\n    loop.run_until_complete(future)\n  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete\n    self.run_forever()\n  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever\n    self._run_once()\n  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once\n    event_list = self._selector.select(timeout)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.12/selectors.py", line 468, in select\n    fd_event_list = self._selector.poll(timeout, max_ev)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 102, in build\n    return await extension.build(additional_hooks=additional_hooks)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 96, in build\n    available_commands = await self._get_available_commands(\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 194, in _get_available_commands\n    output = await check_output(\n             ^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 129, in check_output\n    assert not rc, f\'Expected {args} to pass: {stderr_data}\'\n           ^^^^^^\nAssertionError: Expected [\'/usr/bin/python3\', \'-W\', \'ignore:setup.py install is deprecated\', \'-W\', \'ignore:easy_install command is deprecated\', \'setup.py\', \'--help-commands\'] to pass: Traceback (most recent call last):\n  File "/home/p/ros2_ws/src/scan_to_pointcloud/setup.py", line 1, in <module>\n    from setuptools import find_packages, setup\n  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 7, in <module>\n    import _distutils_hack.override  # noqa: F401\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/_distutils_hack/override.py", line 1, in <module>\n    __import__(\'_distutils_hack\').do_override()\n  File "/usr/lib/python3/dist-packages/_distutils_hack/__init__.py", line 77, in do_override\n    ensure_local_distutils()\n  File "/usr/lib/python3/dist-packages/_distutils_hack/__init__.py", line 60, in ensure_local_distutils\n    importlib.import_module(\'distutils\')\n  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import\n  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 1262, in _find_spec\n  File "/usr/lib/python3/dist-packages/_distutils_hack/__init__.py", line 97, in find_spec\n    return method()\n           ^^^^^^^^\n  File "/usr/lib/python3/dist-packages/_distutils_hack/__init__.py", line 108, in spec_for_distutils\n    mod = importlib.import_module(\'setuptools._distutils\')\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/setuptools/_distutils/__init__.py", line 12, in <module>\n    importlib.import_module(\'_distutils_system_mod\')\n  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.12/_distutils_system_mod.py", line 15, in <module>\n    import distutils.command.install as orig_install\n  File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 12, in <module>\n    from ..core import Command\n  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 23, in <module>\n    from .cmd import Command\n  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 13, in <module>\n    from . import util, dir_util, file_util, archive_util, dep_util\n  File "/usr/lib/python3/dist-packages/setuptools/_distutils/archive_util.py", line 11, in <module>\n    import zipfile\n  File "/usr/lib/python3.12/zipfile/__init__.py", line 12, in <module>\n    import struct\n  File "/usr/lib/python3.12/struct.py", line 13, in <module>\n    from _struct import *\n  File "<frozen importlib._bootstrap>", line 1357, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 418, in __enter__\n  File "<frozen importlib._bootstrap>", line 311, in acquire\nKeyboardInterrupt\n\n'}
[0.631677] (scan_to_pointcloud) JobEnded: {'identifier': 'scan_to_pointcloud', 'rc': 'SIGINT'}
[0.640879] (-) EventReactorShutdown: {}
